grpc:
  port: 8090
  enable-reflection: true
spring:
  jmx:
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://mytenent.auth0.com/"
logging :
  level:
    root : debug
security:
  basic:
    enabled: true
management:
  security:
    enabled: true
auth0:
  audience: "https://api.example.com"
rbac:
  scope: "profile:read"
