grpc:
  port: 8080
  enable-reflection: true
spring:
  main:
    allow-bean-definition-overriding: true
  jmx:
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://mytenant.auth0.com/"
logging :
  level:
    root : debug
security:
  basic:
    enabled: true
management:
  security:
    enabled: true
auth0:
  audience: "https://apis.dev.example.com"
